CREATE EXTENSION IF NOT EXISTS vector;
CREATE TABLE IF NOT EXISTS users (
    username TEXT PRIMARY KEY,
    password TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS document (
    id SERIAL PRIMARY KEY,
    filename TEXT,
    user_id TEXT REFERENCES users(username) ON DELETE CASCADE,
    summary TEXT,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);